const Actions = {
  GET_ALL_PROBLEMS: "PROBLEMS/GET_ALL_PROBLEMS",
  SET_ALL_PROBLEMS: "PROBLEMS/SET_ALL_PROBLEMS",
  GET_MORE_PROBLEMS: "PROBLEMS/GET_MORE_PROBLEMS",
  SET_MORE_PROBLEMS: "PROBLEMS/SET_MORE_PROBLEMS",
  ADD_PROBLEM: "PROBLEMS/ADD_PROBLEM",
  SET_RESULT_PROBLEM_STATUS: "PROBLEMS/SET_RESULT_PROBLEM_STATUS",
  RESET_RESULT_PROBLEM_STATUS: "PROBLEMS/RESET_RESULT_PROBLEM_STATUS",
  DELETE_PROBLEM: "PROBLEM/DELETE_PROBLEM",
  EDIT_PROBLEM: "PROBLEM/EDIT_PROBLEM",
  SET_EDITED_PROBLEM: "PROBLEM/SET_EDITED_PROBLEM",
};

export default Actions;
