const Actions = {
  GET_ALL_PROBLEMS: "PROBLEMS/GET_ALL_PROBLEMS",
  SET_ALL_PROBLEMS: "PROBLEMS/SET_ALL_PROBLEMS",
  GET_MORE_PROBLEMS: "PROBLEMS/GET_MORE_PROBLEMS",
  SET_MORE_PROBLEMS: "PROBLEMS/SET_MORE_PROBLEMS",
};

export default Actions;
