const Actions = {
  SET_SEARCH_STR: "SEARCH/SET_SEARCH_STR",
  SET_IS_ACTUAL: "SEARCH/SET_IS_ACTUAL",
  SET_IS_DONE: "SEARCH/SET_IS_DONE",
  SET_ORDER_VALUE: "SEARCH/SET_ORDER_VALUE",
  SET_ADDITIONAL_SEARCH_DATA: "SEARCH/SET_ADDITIONAL_SEARCH_DATA",
  RESET_ADDITIONAL_SEARCH_DATA: "SEARCH/RESET_ADDITIONAL_SEARCH_DATA",
};

export default Actions;
