const Actions = {
  SET_SEARCH_STR: "SEARCH/SET_SEARCH_STR",
  SET_IS_ACTUAL: "SEARCH/SET_IS_ACTUAL",
  SET_IS_DONE: "SEARCH/SET_IS_DONE",
  SET_DATE_RANGE: "SEARCH/SET_DATE_RANGE",
  SET_AREAS: "SEARCH/SET_AREAS",
  SET_PROBLEM_CODES: "SEARCH/SET_PROBLEM_CODES",
  SET_ORDER_VALUE: "SEARCH/SET_ORDER_VALUE",
};

export default Actions;
