const Actions = {
  TRY_LOGIN: "USER/TRY_LOGIN",
  TRY_LOGOUT: "USER/TRY_LOGOUT",
  GET_USER: "USER/GET_USER",
  SET_USER: "USER/SET_USER",
  RESET_USER: "USER/RESET_USER",
  SET_ERROR_LOGIN: "USER/SET_ERROR_LOGIN",
};

export default Actions;
